name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Create Version

    runs-on: ubuntu-latest

    env:
      APP_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set variables
        id: version
        run: echo ::set-output name=version::$(cat VERSION)

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
